type: "mediapipe.tasks.vision.face_landmarker.FaceBlendshapesGraph"

input_stream: "LANDMARKS:face_landmarks"
input_stream: "IMAGE_SIZE:image_size"
output_stream: "BLENDSHAPES:face_blendshapes"

node {
  calculator: "mediapipe.tasks.vision.face_landmarker.FaceBlendshapesGraph"  # Ensure namespace matches if needed
  input_stream: "LANDMARKS:face_landmarks"
  input_stream: "IMAGE_SIZE:image_size"
  output_stream: "BLENDSHAPES:face_blendshapes"
  options {
    [mediapipe.tasks.vision.face_landmarker.proto.FaceBlendshapesGraphOptions.ext]
    {
      base_options {
        model_asset {
          file_name: "face_blendshapes.tflite"
        }
      }
    }
  }
}